rules:
  earth-required-properties:
    message: 'Links need to have a {{property}}'
    given: '$'
    then:
      - field: title
        function: truthy
      - field: description
        function: truthy
      - field: url
        function: truthy

  earth-schema:
    message: '{{error}}'
    recommended: true
    given: '$'
    then:
      function: schema
      functionOptions:
        schema:
          type: object
          properties:
            title:
              type: string
            url:
              type: string
              format: url
            countries:
              type: array
              items:
                type: string
                minItems: 1
                pattern": '^[A-Z]{2}$'
            categories:
              type: array
              items:
                type: string
            tags:
              type: array
              maxLength: 5
              items:
                type: string
            description:
              type: string
              maxLength: 500
            featured:
              type: boolean
            image:
              type: [string, 'null']
          required:
            - categories
            - description
          additionalProperties: false
